# Spring Boot configuration
spring:
  profiles:
    active: dev
---
spring:
  application:
    name: boleta
  profiles: dev
# Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://des1081.tecnova.cl:5432/apirest?createDatabaseIfNotExist=true
    username: apirest
    password: Tatio2019
    tomcat:
     initial-size: 3
     max-active: 3
     max-idle: 3
     min-idle: 3
     max-wait: 20000
# Spring-Admin    
  boot:
    admin:
      client:
        url:
        -   http://elqui.tecnova.cl:9000      
        username: admin
        password: admin-password       
# JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

---
spring:
  application:
    name: boleta
  profiles: prod
# Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://algarrobo.tecnova.cl:5432/apirest?createDatabaseIfNotExist=true
    username: apirest
    password: Tatio2019
    tomcat:
     initial-size: 3
     max-active: 3
     max-idle: 3
     min-idle: 3
     max-wait: 20000
# Spring-Admin    
  boot:
    admin:
      client:
        url:
        -   http://elqui.tecnova.cl:9000      
        username: admin
        password: admin-password       
# JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

---
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"    
  level:
    org.springframework: INFO
    org.hibernate: DEBUG
  file: logs/application-boleta.log
# Server configuration
server:
  tomcat:
    max-threads: 3    
  port: 6001
  sessionTimeout: 30
  error:
    include-stacktrace: always
    
#Spring Boot Admin
management:
  endpoints:
    web:
      exposure:
        include: "*"    
  endpoint:
    health:
      show-details: ALWAYS     

properties:
  url.obtenerParametros: http://localhost:6003/api/datosTipo/obtenerParametros/
